version: 2

project_name: openax

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: .
    id: openax
    binary: openax
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "amd64"
      - "arm64"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: imtanmoy
    name: openax
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## OpenAx {{ .Tag }}

    Welcome to this new release of OpenAx! 🚀

    ### Installation

    #### npm
    ```bash
    npm install -g openax-cli
    ```

    #### Binary Download
    Download the appropriate binary for your platform from the assets below.

    #### Go Install
    ```bash
    go install github.com/imtanmoy/openax@{{ .Tag }}
    ```

  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}! Come chat with us on [GitHub Discussions](https://github.com/imtanmoy/openax/discussions) and feel free to reach out if you have any questions.

    **Full Changelog**: https://github.com/imtanmoy/openax/compare/{{ .PreviousTag }}...{{ .Tag }}
